server:
  port: 8081


spring:
  cloud:
    config:
      enabled: false

  datasource:
    url: jdbc:mysql://localhost:3306/usuarios
    username: root
    password: 1234

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
appDescription: "Administrar usuarios de las plazoletas"
appVersion: "1.0.0"

microservice:
  restaurantServiceUrl: http://localhost:8082/api/user/
